// <auto-generated />
namespace _24HourBuild.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _10oclockadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10oclockadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202006020211080_10oclockadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
